language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache

matrix:
  fast_finish: true
  include:
      - python: "2.7"
        env: PLONE_VERSION="5.2" TARGET=test
      - python: "3.6"
        env: PLONE_VERSION="5.2" TARGET=test
      - python: "3.7"
        env: PLONE_VERSION="5.2" TARGET=test
      - python: "3.8"
        env: PLONE_VERSION="5.2" TARGET=test
      - python: "3.8"
        env: PLONE_VERSION="5.2" TARGET=code-analysis

before_install:
    - virtualenv -p `which python` .
    - mkdir $HOME/.buildout
    - mkdir -p $HOME/buildout-cache/{downloads,eggs,extends}
    - echo "[buildout]" > $HOME/buildout.cfg
    - echo "extends = test_plone$PLONE_VERSION.cfg" >> $HOME/buildout.cfg
    - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/buildout.cfg
    - bin/pip install -r requirements.txt
    - bin/buildout -N -t 3 annotate

install:
  - bin/buildout -N -q -t 3
script:
  - bin/$TARGET
after_success:
  - if test "$TARGET" == "coverage.sh"; then pip install -q coveralls && coveralls || true; fi
